#!/bin/bash
cd "$(dirname "$(readlink -f "$0")")"
pwd
if  cmp -s /opt/geph4-client ./geph4-client
    then 
    echo "already works"
else
    echo "escalate permissions for geph4-vpn-helper"
    export DIR="$(pwd)"
    pkexec sh -c "cp '$DIR/geph4-vpn-helper' /opt/geph4-vpn-helper && chown root /opt/geph4-vpn-helper && chmod -w /opt/geph4-vpn-helper && chmod u+s /opt/geph4-vpn-helper && cp '$DIR/geph4-client' /opt/geph4-client && chmod +x /opt/geph4-client"
fi